### ISSUE TITLE
Enabling this module blocks batch operations

### ISSUE THREAD

**Issue by ChuanD** [leymannx/drupal-ckeditor-timestamp#2]
Hi,
using this module solves mentioned issues, but somehow possibly causes all batch operations (*/batch?op=start&id=xy) to get stuck before initialization with no progress.

Steps to reproduce:
- install and activate CKEditor Timestamp module
- attempt to delete any user OR try to perform any other batch operation
- observe absence of progress

Thanks for the module anyways, it helped.

**Comment by normanlolx** [comment]
I can't reproduce this behaviour. I implemented the examples from https://api.drupal.org/api/examples/batch_example%21batch_example.module/7.x-1.x and run the batches successfully with ckeditor_timestamp module activated.

Also deleting user's while ckeditor_timestamp module is activated was no problem.

**Comment by normanlolx** [comment]
Apart from that, you are supposed to have this module only enabled during development. So that you enable the module, develop your CKEditor plugin, and then switch this module off again.
